name: VitalSuicide
version: @version@
main: com.tamrielnetwork.vitalsuicide.VitalSuicide
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives you the ability to commit suicide.
commands:
  suicide:
    description: "Main command"
    usage: "/suicide"
permissions:
  vitalsuicide.suicide:
    description: "Permission to commit suicide"
    default: op